name: CI

on:
  issues:
    types: [created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        curl https://api.github.com/repos/haodedong/Blog/issues >> issues.md
        git config --global user.email "haodedong1996@163.com"
        git config --global user.name "haodedong"
        git add .
        git commit -m "test"
        git push -u origin master -f 
